import type { Metadata } from "next";
import { Geist, Geist_Mono, Yeon_Sung } from "next/font/google";
import '@/styles/globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const yeonSung = Yeon_Sung({
  variable: "--font-yeon-sung",
  subsets: ["latin"],
  weight: ["400"],   
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${yeonSung.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
